sudo: required

language: python

cache:
  pip: true

python:
- "3.6"

install:
- pip install pipenv
- pip install pytest pytest-cov codecov
- pipenv install

script:
- pipenv run python -m pytest --cov=./

after_success:
- codecov