sudo: required
language: python
cache:
  pip: true
python:
- '3.6'
install:
- pip install pipenv
- pip install pytest pytest-cov codecov
- pipenv install
script:
- pipenv run python -m pytest --cov=./
after_success:
- codecov
deploy:
  provider: pypi
  user: siku2
  password:
    secure: AxQk2O/hH0G2o8PglWf97P5g0OXNW9weY+V5upzZrjt4x5NeohWGFcaI+zZdzRk3VO4aAlPNLZbtfBn8d7BJff0bD2uoY9UdmZRrGcCJnUuP3VY8wERwwE+pCvCxxEDjrAbmJPi0n8QMlvcl3RCCLduYR28AKL9mnRGg6UIc9O3CcjU0GSEuohrMdcO3UI+B0XYXK8z7nCv1VdJxDYAJBXjIlESiG3kaOClXl0YWN9TQsMcfzlhFCL0T8InT3siX3+dRdbVcpOjscZV4oir1eVjWHsydLDuX9Icv/if5Llj3sIzRukgMzKm85+e4ACsLetnwhnT3lxR8y1bY9OQlZPnjOfwMjl3qfhClsJ8vB8QOe2HwuOKHJOSpN46e500J0kIwtU1FmWeQRmBcfkitm14ltvK6c3t0+DfCI9zzxhyv9TUiNsBQFSuZd2a5WRWlBao0ShDOt3biV99+7/mELNta0RCUOKpgEScdiQhSF9tqG/4JBpXIzSmokt9s6vjSW7Qx1o2vF1U8kpdZtel+NzVLGgOilulTHDpaHRDlYhnTlVWnElsxBG+JRs1gtrnJDPnNjW5qiZDkWNwV2hlItdn0pMneZJ1N2kElmhLsYTPV44Hq6R4z5PTPZmmfjG3vD6uMrdkvrVr4NhJ2ZHFA5Xvy6ctt4/nt4f795/hPEmE=
  true:
    branch: master